Do not reconcile if `modelmesh` annotation set as true.
kserve/kserve pull request #1851
Opened 2021-10-04 11:25 UTC by ScrapCodes

**What this PR does / why we need it**:
When annotation : 
`"serving.kserve.io/deploymentMode": "ModelMesh" ` is set. kserve controllers (single model) should not reconcile.

e.g.:

```yaml
apiVersion: "serving.kserve.io/v1beta1"                                                                                                                                                                               
kind: "InferenceService"                                                                                                                                                                                              
metadata:
  name: "sklearn-iris2"   
  annotations:     
      "serving.kserve.io/deploymentMode": "ModelMesh"                                                                                                                                                                 spec:                                                                                                                                                                                                                 
  predictor:   
    sklearn:                                                                                                                                                                                                          
      storageUri: "gs://kfserving-samples/models/sklearn/iris"                                                                                                                                                        
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
support "serving.kserve.io/deploymentMode": "ModelMesh" annotation.
```

2021-10-04 17:47 UTC, pvaneck requested changes
Thanks @ScrapCodes! Just needs some minor adjustments, and I think it should be good to go.

2021-10-04 17:47 UTC, pvaneck commented on pkg/controller/v1beta1/inferenceservice/controller.go
> +	if isvcutils.GetDeploymentMode(annotations, deployConfig) == constants.ModelMeshDeployment {
Let's store the output of the `GetDeploymentMode` call here and use that in the RawDeployment check below.

2021-10-04 17:47 UTC, pvaneck commented on pkg/controller/v1beta1/inferenceservice/controller.go
> +	}
Let's maybe move this logic above the `finalizerName := "inferenceservice.finalizers"` line above, as I don't think we need the custom finalizer being added in the case of a ModelMesh deployment.

2021-10-04 17:47 UTC, pvaneck commented on pkg/controller/v1beta1/inferenceservice/controller.go
> +		r.Log.Info(string(constants.ModelMeshDeployment), " is set as ", constants.DeploymentMode,
Log message has mismatched key-value pairs. Suggestion to clean up the message a bit:
```golang
r.Log.Info("Skipping reconciliation for InferenceService", constants.DeploymentMode, deploymentMode,
    "apiVersion", isvc.APIVersion, "isvc", isvc.Name)
```

2021-10-05 06:14 UTC, ScrapCodes commented
@pvaneck Thanks, updated the PR.

2021-10-05 14:22 UTC, pvaneck reviewed
Thanks @ScrapCodes!

/lgtm

2021-10-05 16:20 UTC, yuzisun commented
/approve

2021-10-05 16:21 UTC, merged