Add helm chart for KServe
kserve/kserve pull request #1878
Opened 2021-10-25 00:44 UTC by yuzisun

**What this PR does / why we need it**:
This PR adds the helm chart for installing kserve and modelmesh

## Install KServe
`helm install kserve manifests/charts -n kserve`

## Upgrade KServe
 `kubectl apply -f manifests/charts/crds`
`helm upgrade kserve manifests/charts -n kserve`

## Uninstall KServe
`helm uninstall kserve`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

2021-10-28 00:36 UTC, pvaneck requested changes
Thanks, @yuzisun. For the modelmesh related yaml, I had to make a few changes to get things to work which I added inline. After that, the deployment using helm worked well, and I as able to deploy a predictor (after configuring etcd).

2021-10-28 00:36 UTC, pvaneck commented on manifests/charts/templates/deployment.yaml
> +        image: {{ .Values.kserve.modelmesh-controller.image }}
```suggestion
        image: {{ .Values.kserve.modelmesh.controller.image }}
```

2021-10-28 00:36 UTC, pvaneck commented on manifests/charts/templates/rolebinding.yaml
> +  name: controller-leader-election-rolebinding
```suggestion
  name: modelmesh-controller-leader-election-rolebinding
```

2021-10-28 00:36 UTC, pvaneck commented on manifests/charts/templates/rolebinding.yaml
> +  name: controller-leader-election-role
```suggestion
  name: modelmesh-controller-leader-election-role
```

2021-10-28 00:36 UTC, pvaneck commented on manifests/charts/templates/rolebinding.yaml
> +  name: controller-role
```suggestion
  name: modelmesh-controller-role
```

2021-10-28 00:36 UTC, pvaneck commented on manifests/charts/values.yaml
> +      modelmeshRuntimeAdapterTag: v0.7.0
```suggestion
      modelmeshRuntimeAdapterImageTag: v0.7.0
      restProxyImage: kserve/rest-proxy
      restProxyImageTag: v0.1.1
```

2021-10-28 11:54 UTC, yuzisun commented
> Thanks, @yuzisun. For the modelmesh related yaml, I had to make a few changes to get things to work which I added inline. After that, the deployment using helm worked well, and I as able to deploy a predictor (after configuring etcd).

Thanks @pvaneck ! Forgot to run another test after adding MM template variables, updated the PR now.

2021-10-29 05:55 UTC, pvaneck reviewed
/lgtm

2021-10-29 05:55 UTC, merged