Storage initializer ca bundle mount
kserve/kserve pull request #2906
Opened 2023-05-16 02:11 UTC by danilopeixoto

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2897

**Type of changes**
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Feature/Issue validation/testing**:

Please describe the tests that you ran to verify your changes and relevent result summary. Provide instructions so it can be reproduced.
Please also list any relevant details for your test configuration.

- [x] Test injected CA bundle secret volume
- [x] Test not injected CA bundle secret volume

- Logs

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Checklist**:

- [x] Have you added unit/e2e tests that prove your fix is effective or that this feature works?
- [x] Has code been commented, particularly in hard-to-understand areas?
- [x] Have you made corresponding changes to the documentation?

**Release note**:

```release-note
Custom CA bundle for storage initializer
```

2023-07-04 21:33 UTC, yuzisun commented on config/configmap/inferenceservice.yaml
> +        "caBundleSecretName": "",
@danilopeixoto I guess this secret is required to be created for each namespace where the inference service pod is running right?

2023-07-25 04:21 UTC, Jooho commented
@danilopeixoto @yuzisun  This is a great idea and I also look for the same thing. In my opinion, this functionality should be supported using annotations at the inference service level. The reason is that not all inference services necessarily need to use the same CA bundle. Therefore, there is no need to create unnecessary cabundle secrets in all Kserve namespaces. By utilizing annotations, each inference service can specify its own required CA bundle, making the configuration more flexible and efficient. What do you think?

2023-08-28 17:44 UTC, Jooho commented
@yuzisun @danilopeixoto does this PR move forward?

2023-09-13 12:45 UTC, yuzisun commented
> @yuzisun @danilopeixoto does this PR move forward?

Yes sorry for the delay, meanwhile can you help resolve the conflicts ?

2023-09-13 13:51 UTC, Jooho commented
@yuzisun I can definitely help this PR but I am not sure how I can add a new commit to solve this conflicts.
Do I need to send a new PR based on @danilopeixoto's PR ?

2023-10-07 13:58 UTC, yuzisun commented
> @yuzisun I can definitely help this PR but I am not sure how I can add a new commit to solve this conflicts. Do I need to send a new PR based on @danilopeixoto's PR ?

@Jooho I resolved the conflicts, could you help test the PR?

2023-10-27 16:50 UTC, Jooho commented
@yuzisun sorry for the late response. 
I think we need to extend this pr more. This is my idea regarding ca bundle support. We need 2 options : global, isvc specific. If users set the cabundle secret to global configuration configMap, kserve operator needs to create the secret (ca bundle) per each user namespace. but if users want to use their own secret(cabundle) in the namespace, it needs to be possible to set the secret(ca bundle) with an inferenceService.
If there is a specific annotation specified in an inferenceServince, kserve operator should not create a global secret in a namespace and use the secret user specified in the user namespace. 
@yuzisun @ckadner What do you think?
this is a very high-level diagram.
![image](https://github.com/kserve/kserve/assets/2375181/889bf25a-591b-4615-b761-834b33bebd97)

2023-10-27 16:57 UTC, Jooho commented
We can work separately. The first global option then isvc annotation.

By the way, this pr missed creating a secret in each namespace. This needs to be added.

2023-10-29 18:36 UTC, yuzisun commented
> We can work separately. The first global option then isvc annotation.
> 
> By the way, this pr missed creating a secret in each namespace. This needs to be added.

Thanks for the explanation! I think it makes sense, we can limit this PR to be the global scoped CA secret and create a separate PR for implementing the namespace level CA bundle annotation. I have a question though, how do you plan to provision the CA secrets to the user namespaces ? we do not know which namespaces are kserve user namespaces.

2023-10-31 18:26 UTC, ckadner requested changes
I created a development branch `ca_bundle_colab` and a corresponding PR #3216 so @danilopeixoto and @Jooho can work together to complete the work started in this PR

I'm leaving this PR open for now, but set it into draft mode. Once the work is completed on PR #3216, with @danilopeixoto and @Jooho as co-authors, this PR should be closed.

2023-11-15 20:00 UTC, ckadner commented
> I created a development branch `ca_bundle_colab` and a corresponding PR #3216 so @danilopeixoto and @Jooho can work together to complete the work started in this PR
> 
> I'm leaving this PR open for now, but set it into draft mode. Once the work is completed on PR #3216, with @danilopeixoto and @Jooho as co-authors, this PR should be closed.

The collaboration branch idea did not pan out. @Jooho just created a new PR with all of @danilopeixoto commits to establish co-authorship

https://github.com/kserve/kserve/pull/3250

2023-11-15 20:00 UTC, closed without merging