add default deployment and fix startup without knative
kserve/kserve pull request #52
Opened 2021-09-07 11:54 UTC by Iamlovingit

**What this PR does / why we need it**:

1. Add `deploymentMode` config item in inferenceservice configmap.

```
deploy: |-
    {
      "defaultDeploymentMode": "Serverless"
    }
```

* The `defaultDeploymentMode` support tow modes: `Serverless` and `RawDeployment`, others value will make errors.
* If `defaultDeploymentMode` is `RawDeployment`, kserve-manager can startup without knative.
* If user wants different deploy mode from default mode, add an annotation in isvc's annotation:
  `"serving.kserve.io/deploymentMode": "RawDeployment"` or `"serving.kserve.io/deploymentMode": "Serverless"`

2. Fix controller start failed when there is no knative.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
https://github.com/kubeflow/kfserving/issues/1768

2021-09-07 11:56 UTC, Iamlovingit commented
/assign @yuzisun

2021-09-07 12:05 UTC, pugangxa commented
/lgtm

2021-09-08 21:40 UTC, pvaneck requested changes
Thanks for this. I think this will be useful when we add `Modelmesh` as a deployment mode in the near future. Left a few comments.

2021-09-08 21:40 UTC, pvaneck commented on pkg/controller/v1beta1/inferenceservice/controller.go
> +			Owns(&v1alpha3.VirtualService{}).
In  `RawDeployment` mode, no istio virtualservices are being generated, right? So probably don't need this `Owns` line.

2021-09-08 21:40 UTC, pvaneck commented on pkg/controller/v1beta1/inferenceservice/controller.go
> +func GetDeployConfig() (*v1beta1api.DeployConfig, error) {
Can the `NewDeployConfig` function be reused? I'm thinking it might be cleaner to get the deploy config in main.go, then pass the deploymentMode string as an argument to `SetupWithManager` below.

2021-09-08 21:40 UTC, pvaneck commented on cmd/manager/main.go
>  	log.Info("Setting up Istio schemes")
Perhaps add the istio `AddToScheme` under the `deployConfig.DefaultDeploymentMode == "Serverless"` block as well since it's specific to Serverless mode.

2021-09-08 21:40 UTC, pvaneck commented on cmd/manager/main.go
>  	// Setup all Controllers
As mentioned below regarding getting the  deploy config in main.go, you can probably  just do:

```
	cl, err := client.New(mgr.GetConfig(), client.Options{Scheme: mgr.GetScheme()})
        ... 
	deployConfig, err := v1beta1.NewDeployConfig(cl)
```
This needs to be done after the core scheme is added.
Then pass `deployConfig.DefaultDeploymentMode` to  the InferenceServiceReconciler `SetupWithManager` function.

2021-09-09 02:03 UTC, Iamlovingit commented on pkg/apis/serving/v1beta1/configmap.go
> +			return nil, fmt.Errorf("Invalid deployment mode, support Serverless and RawDeployment")
ye, this is better.

2021-09-09 02:04 UTC, Iamlovingit commented on pkg/controller/v1beta1/inferenceservice/utils/utils.go
> +case 1: no serving.kubeflow.org/deploymentMode annotation
oh, I forgot this, Iet me check it again.

2021-09-09 02:05 UTC, Iamlovingit commented on pkg/controller/v1beta1/inferenceservice/controller.go
> +			Owns(&v1alpha3.VirtualService{}).
yes

2021-09-09 02:11 UTC, Iamlovingit commented on cmd/manager/main.go
>  	// Setup all Controllers
oh, let me try this. I have tested to use mgr.GetClient(), but this is not working until the server is started.

2021-09-09 06:25 UTC, Iamlovingit commented on cmd/manager/main.go
>  	// Setup all Controllers
I have tested this, but it is not working. At beginning, we can not use `mgr.GetClient()` to get configmap from cluster.  Do you have any new suggestions about this issue?
Now the implementation is:
1. Before server started: use `kubernetes.clientset`
2. After server started: use `controller-runtime.client`

2021-09-09 07:09 UTC, pvaneck commented on cmd/manager/main.go
>  	// Setup all Controllers
Right, the client I was suggesting was not the `mgr.GetClient()` client, but a new one. Can you try the following:
```go
	cl, err := client.New(mgr.GetConfig(), client.Options{Scheme: mgr.GetScheme()})
	if err != nil {
		setupLog.Error(err, "unable to create client")
		os.Exit(1)
	}

	deployConfig, err := v1beta1.NewDeployConfig(cl)
	if err != nil {
		log.Error(err, "unable to get deploy config.")
		os.Exit(1)
	}

	if deployConfig.DefaultDeploymentMode == "Serverless" {
            ...
	}
```
where `client` is `sigs.k8s.io/controller-runtime/pkg/client` .

2021-09-09 07:54 UTC, Iamlovingit commented on cmd/manager/main.go
>  	// Setup all Controllers
got it. will try this

2021-09-09 10:47 UTC, Iamlovingit commented on cmd/manager/main.go
>  	// Setup all Controllers
It works! Thanks! @pvaneck

2021-09-10 01:45 UTC, pvaneck requested changes
Looking good. Just a few more things I noticed. 

Also, I noticed that this PR wants to merge into the `kserve` branch and not the `master` branch. Is this intended?

2021-09-10 01:45 UTC, pvaneck commented on pkg/controller/v1beta1/inferenceservice/controller.go
> +	}
Let's remove this chunk and instead  pass in the deployment mode to this function as a parameter.

```go
func (r *InferenceServiceReconciler) SetupWithManager(mgr ctrl.Manager, deployMode string) error {
    if deployMode == "RawDeployment" {
        ...
```

In main.go, can pass in `deployConfig.DefaultDeploymentMode` into where `SetupWithManager` is called.

2021-09-10 01:45 UTC, pvaneck commented on cmd/manager/main.go
> +		log.Error(err, "unable to new client.")
unable to new client -> unable to create new client

2021-09-10 07:29 UTC, yuzisun commented on pkg/controller/v1beta1/inferenceservice/controller.go
> +			//Owns(&v1alpha3.VirtualService{}).
Remove the commented out lines and the controller should also "own" the core service and ingress resource we created.

2021-09-10 07:31 UTC, yuzisun commented
> Looking good. Just a few more things I noticed.
> 
> Also, I noticed that this PR wants to merge into the `kserve` branch and not the `master` branch. Is this intended?

@Iamlovingit please help switch to master branch, thanks.

2021-09-13 08:21 UTC, Iamlovingit commented
switch to #57

2021-09-13 08:21 UTC, Iamlovingit commented
switch to #57

2021-09-13 08:21 UTC, closed without merging

2021-09-13 08:21 UTC, Iamlovingit commented
switch to #57